exec-once = swaybg -i /home/xfof/.config/hypr/wallpapers/1.jpg
exec-once = eww daemon
exec-once = eww open bar
exec-once = eww open calendar
exec-once = eww open sound
exec-once = eww open dashboard
exec-once = hyprctl setcursor rose-pine 24
exec-once = /home/xfof/.config/eww/scripts/variables.sh reset_all
